# ftt_joint_multitask_5fold_cv.py
# -----------------------------------------------------
# FT-Transformer joint model (multi-task: regression + multi-label binary)
# ** 5-Fold Cross-Validation version **
#
# Loads:
#   BASE/x.csv                – full predictor matrix
#   BASE/y_cont.csv           – full continuous responses
#   BASE/y_bin.csv            – full binary responses
#   BASE/fold_assignments.csv – generated by the baseline R script
#
# For each fold:
#   - Standardises X using TRAINING FOLD stats only (no leakage)
#   - Holds out an internal 90/10 split of the training fold for early stopping
#   - Trains FT-Transformer with masked MSE + masked BCE losses
#   - Evaluates on the test fold
#
# Outputs (all in OUT_DIR):
#   cv_all_folds_metrics.csv     – per-variable metrics for every fold
#   cv_per_variable_metrics.csv  – mean & variance per toxin across folds
#   cv_overall_metrics.csv       – single overall mean & variance (for paper)
# -----------------------------------------------------

import os, random, platform
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
import rtdl_revisiting_models as rtdl
from sklearn.metrics import r2_score, roc_auc_score, f1_score, accuracy_score

os.environ["PYTORCH_MPS_HIGH_WATERMARK_RATIO"] = "0.0"

# ── Config ─────────────────────────────────────────────────────────────
SEED     = 42
BASE     = "/Users/alaninglis/Desktop/Mycotoxin Paper Final"   # R project — data lives here
OUT_DIR  = "/Users/alaninglis/Desktop/Transfer Learning models/FT Transformer/ftt_results"
os.makedirs(OUT_DIR, exist_ok=True)

CONT = [
    "DON", "D3G", "Nivalenol", "3-AC-DON", "15-AC-DON",
    "T-2_toxin", "HT-2_toxin", "T2G", "Neos",
    "ENN_A1", "ENN_A", "ENN_B", "ENN_B1", "BEAU", "ZEN",
    "Apicidin", "STER", "DAS", "Quest", "AOH", "AME", "MON",
    "Ergocristine", "EGT"
]
BIN      = [f"{t}_bin" for t in CONT]
N_CONT   = len(CONT)
N_BIN    = len(BIN)

N_FOLDS  = 5
BS       = 128
MAX_E    = 60
PATIENCE = 8
LR       = 3e-3
D_BLOCK  = 192
N_BLOCKS = 2
VAL_FRAC = 0.10    # internal early-stopping fraction, carved from training fold only


# ── Reproducibility ────────────────────────────────────────────────────
def set_seeds(seed):
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seeds(SEED)


# ── Device ─────────────────────────────────────────────────────────────
if torch.cuda.is_available():
    DEV, AMP, AMP_DTYPE = "cuda", True, torch.float16
    scaler = torch.cuda.amp.GradScaler()
elif torch.backends.mps.is_available():
    DEV, AMP, scaler, AMP_DTYPE = "mps", False, None, None
else:
    DEV, AMP, scaler, AMP_DTYPE = "cpu", False, None, None

print(f"Using device: {DEV}")


# ── Masked losses ──────────────────────────────────────────────────────
def masked_mse(pred, tgt, msk):
    diff  = (pred - tgt).pow(2) * msk.float()
    denom = msk.sum().clamp(min=1)
    return diff.sum() / denom

def masked_bce(probs, tgt, msk):
    bce   = nn.functional.binary_cross_entropy(probs, tgt, reduction="none")
    denom = msk.sum().clamp(min=1)
    return (bce * msk.float()).sum() / denom


# ── Helpers ────────────────────────────────────────────────────────────
def to_float_matrix(df):
    return pd.DataFrame(
        {c: pd.to_numeric(df[c], errors="coerce") for c in df.columns}
    ).values.astype(np.float32)

def make_loader(X, Yc, Yb, Mc, Mb, bs, shuffle):
    num_workers = 0 if platform.system() == "Darwin" else max(os.cpu_count() or 1, 1)
    ds = TensorDataset(X, Yc, Yb, Mc, Mb)
    return DataLoader(ds, batch_size=bs, shuffle=shuffle, num_workers=num_workers)

def rmse_safe(y_true, y_pred):
    try:
        from sklearn.metrics import root_mean_squared_error
        return float(root_mean_squared_error(y_true, y_pred))
    except Exception:
        from sklearn.metrics import mean_squared_error
        return float(np.sqrt(mean_squared_error(y_true, y_pred)))

def reorder_with_aliases(df, expected, alias_map, label):
    """Reorder df columns to match `expected`, resolving common aliases."""
    resolved, missing = [], []
    for name in expected:
        candidates = [name] + alias_map.get(name, [])
        found = next((c for c in candidates if c in df.columns), None)
        if found is None:
            missing.append(name)
        else:
            resolved.append(found)
    if missing:
        raise ValueError(
            f"{label}: missing columns after alias matching: {missing}\n"
            f"Present: {list(df.columns)}"
        )
    return df.loc[:, resolved]

alias_cont = {
    "3-AC-DON":   ["X3.AC.DON",  "3_AC_DON",  "X3_AC_DON"],
    "15-AC-DON":  ["X15.AC.DON", "15_AC_DON", "X15_AC_DON"],
    "T-2_toxin":  ["T.2_toxin",  "T2_toxin",  "T_2_toxin"],
    "HT-2_toxin": ["HT.2_toxin", "HT2_toxin", "HT_2_toxin"],
}
alias_bin = {f"{k}_bin": [f"{v}_bin" for v in vals]
             for k, vals in alias_cont.items()}


# ── Metric computation ─────────────────────────────────────────────────
def compute_fold_metrics(Yc_te, preds_cont, Mc_te,
                         Yb_te, probs_bin,  Mb_te):
    """
    Returns a list of dicts, one per variable, with keys:
        Variable, RMSE, R2, F1_or_Acc, AUC
    Mirrors the R helper functions exactly.
    """
    rows = []

    # Continuous variables
    for j, name in enumerate(CONT):
        mask = Mc_te[:, j]
        if mask.sum() == 0:
            rows.append(dict(Variable=name, RMSE=np.nan, R2=np.nan,
                             F1_or_Acc=np.nan, AUC=np.nan))
            continue
        y = Yc_te[mask, j]
        p = preds_cont[mask, j]
        rmse = rmse_safe(y, p)
        r2   = float(r2_score(y, p)) if len(np.unique(y)) > 1 else np.nan
        rows.append(dict(Variable=name, RMSE=rmse, R2=r2,
                         F1_or_Acc=np.nan, AUC=np.nan))

    # Binary variables
    for j, name in enumerate(BIN):
        mask      = Mb_te[:, j]
        base_name = name.replace("_bin", "")
        if mask.sum() == 0:
            rows.append(dict(Variable=base_name, RMSE=np.nan, R2=np.nan,
                             F1_or_Acc=np.nan, AUC=np.nan))
            continue
        y = Yb_te[mask, j]
        p = probs_bin[mask, j]
        if len(np.unique(y)) == 2:
            y_pred    = (p >= 0.5).astype(int)
            f1_or_acc = float(f1_score(y, y_pred))
            auc       = float(roc_auc_score(y, p))
        else:
            y_pred    = (p >= 0.5).astype(int)
            f1_or_acc = float(accuracy_score(y, y_pred))
            auc       = np.nan
        rows.append(dict(Variable=base_name, RMSE=np.nan, R2=np.nan,
                         F1_or_Acc=f1_or_acc, AUC=auc))

    return rows


# ── Load full dataset ──────────────────────────────────────────────────
print("Loading data...")

X_df    = pd.read_csv(os.path.join(BASE, "x.csv"))
Yc_df   = pd.read_csv(os.path.join(BASE, "y_cont.csv"))
Yb_df   = pd.read_csv(os.path.join(BASE, "y_bin.csv"))
fold_df = pd.read_csv(os.path.join(BASE, "fold_assignments.csv"))

Yc_df = reorder_with_aliases(Yc_df, CONT, alias_cont, "y_cont.csv")
Yb_df = reorder_with_aliases(Yb_df, BIN,  alias_bin,  "y_bin.csv")

X_np  = X_df.select_dtypes(include=[np.number]).values.astype(np.float32)
Yc_np = to_float_matrix(Yc_df)
Yb_np = to_float_matrix(Yb_df)

assert len(fold_df) == len(X_np), \
    f"fold_assignments.csv has {len(fold_df)} rows but data has {len(X_np)}"

fold_assignments = fold_df["fold"].values   # 1-indexed


# ── 5-Fold CV loop ─────────────────────────────────────────────────────
all_fold_metrics = []

for fold_k in range(1, N_FOLDS + 1):

    print(f"\n{'='*60}")
    print(f"  Fold {fold_k} / {N_FOLDS}")
    print(f"{'='*60}")

    # Re-seed each fold (SEED + fold index, consistent with R scripts)
    set_seeds(SEED + fold_k)

    # ── Split ───────────────────────────────────────────────────────────
    test_mask  = (fold_assignments == fold_k)
    train_mask = ~test_mask

    X_train_np  = X_np[train_mask].copy()
    X_test_np   = X_np[test_mask].copy()
    Yc_train_np = Yc_np[train_mask].copy()
    Yc_test_np  = Yc_np[test_mask].copy()
    Yb_train_np = Yb_np[train_mask].copy()
    Yb_test_np  = Yb_np[test_mask].copy()

    # ── Standardise on training fold stats only (no leakage) ────────────
    mu = X_train_np.mean(0, keepdims=True)
    sd = X_train_np.std(0,  keepdims=True); sd[sd == 0] = 1.0
    X_train_np = (X_train_np - mu) / sd
    X_test_np  = (X_test_np  - mu) / sd

    # ── Build masks before zeroing NaNs ─────────────────────────────────
    Mc_train = ~np.isnan(Yc_train_np)
    Mb_train = ~np.isnan(Yb_train_np)
    Mc_test  = ~np.isnan(Yc_test_np)
    Mb_test  = ~np.isnan(Yb_test_np)

    # Keep raw test arrays for metric computation, zero-fill train
    Yc_train_np = np.nan_to_num(Yc_train_np, nan=0.0)
    Yb_train_np = np.nan_to_num(Yb_train_np, nan=0.0)

    # ── Internal 90/10 split within training fold for early stopping ─────
    n_train = X_train_np.shape[0]
    rng     = np.random.default_rng(SEED + fold_k)
    perm    = rng.permutation(n_train)
    cut     = int(n_train * (1 - VAL_FRAC))
    tr_idx, va_idx = perm[:cut], perm[cut:]

    to_f32   = lambda a, idx: torch.tensor(a[idx], dtype=torch.float32)
    to_bool  = lambda a, idx: torch.tensor(a[idx], dtype=torch.bool)

    train_dl = make_loader(
        to_f32(X_train_np,  tr_idx), to_f32(Yc_train_np, tr_idx),
        to_f32(Yb_train_np, tr_idx), to_bool(Mc_train,   tr_idx),
        to_bool(Mb_train,   tr_idx), BS, shuffle=True
    )
    val_dl = make_loader(
        to_f32(X_train_np,  va_idx), to_f32(Yc_train_np, va_idx),
        to_f32(Yb_train_np, va_idx), to_bool(Mc_train,   va_idx),
        to_bool(Mb_train,   va_idx), BS, shuffle=False
    )

    # ── Build fresh model each fold ──────────────────────────────────────
    kw = rtdl.FTTransformer.get_default_kwargs()
    kw.update(n_blocks=N_BLOCKS, d_block=D_BLOCK)

    backbone = rtdl.FTTransformer(
        n_cont_features=X_train_np.shape[1],
        cat_cardinalities=[],
        d_out=None,
        **kw,
    ).to(DEV)

    head_reg = nn.Sequential(nn.Linear(D_BLOCK, N_CONT), nn.ReLU()).to(DEV)
    head_bin = nn.Sequential(nn.Linear(D_BLOCK, N_BIN),  nn.Sigmoid()).to(DEV)

    if DEV == "cuda":
        backbone = torch.compile(backbone, mode="reduce-overhead")

    opt = torch.optim.AdamW(
        list(backbone.parameters()) +
        list(head_reg.parameters()) +
        list(head_bin.parameters()),
        lr=LR
    )

    # ── Training loop ────────────────────────────────────────────────────
    best_val, wait = float("inf"), 0
    ckpt_path = os.path.join(OUT_DIR, f"best_joint_fold{fold_k}.pt")

    for ep in range(1, MAX_E + 1):
        backbone.train(); head_reg.train(); head_bin.train()
        for xb, yc, yb, mc, mb in train_dl:
            xb, yc, yb, mc, mb = (t.to(DEV) for t in (xb, yc, yb, mc, mb))
            opt.zero_grad()
            if AMP:
                with torch.cuda.amp.autocast(dtype=AMP_DTYPE):
                    tok  = backbone(xb, None)
                    loss = masked_mse(head_reg(tok), yc, mc) + \
                           masked_bce(head_bin(tok), yb, mb)
                scaler.scale(loss).backward()
                scaler.step(opt)
                scaler.update()
            else:
                tok  = backbone(xb, None)
                loss = masked_mse(head_reg(tok), yc, mc) + \
                       masked_bce(head_bin(tok), yb, mb)
                loss.backward()
                opt.step()
            if DEV == "mps":
                torch.mps.empty_cache()

        backbone.eval(); head_reg.eval(); head_bin.eval()
        val_loss = 0.0
        with torch.no_grad():
            for xb, yc, yb, mc, mb in val_dl:
                xb, yc, yb, mc, mb = (t.to(DEV) for t in (xb, yc, yb, mc, mb))
                tok = backbone(xb, None)
                val_loss += (masked_mse(head_reg(tok), yc, mc) +
                             masked_bce(head_bin(tok), yb, mb)).item()
        val_loss /= max(len(val_dl), 1)
        print(f"  Epoch {ep:02d}  val_loss = {val_loss:.5f}")

        if val_loss < best_val - 1e-6:
            best_val, wait = val_loss, 0
            torch.save({
                "backbone": backbone.state_dict(),
                "reg":      head_reg.state_dict(),
                "bin":      head_bin.state_dict(),
            }, ckpt_path)
        else:
            wait += 1
            if wait >= PATIENCE:
                print("  Early stopping.")
                break

    # ── Load best weights & predict on test fold ─────────────────────────
    ckpt = torch.load(ckpt_path, map_location=DEV)
    backbone.load_state_dict(ckpt["backbone"])
    head_reg.load_state_dict(ckpt["reg"])
    head_bin.load_state_dict(ckpt["bin"])
    backbone.eval(); head_reg.eval(); head_bin.eval()

    X_test_t = torch.tensor(X_test_np, dtype=torch.float32, device=DEV)
    with torch.no_grad():
        tok_te     = backbone(X_test_t, None)
        preds_cont = head_reg(tok_te).cpu().numpy()
        probs_bin  = head_bin(tok_te).cpu().numpy()

    # ── Metrics for this fold ────────────────────────────────────────────
    fold_rows = compute_fold_metrics(
        Yc_test_np, preds_cont, Mc_test,
        Yb_test_np, probs_bin,  Mb_test
    )
    for row in fold_rows:
        row["fold"] = fold_k
    all_fold_metrics.extend(fold_rows)

    fold_summary = pd.DataFrame(fold_rows)
    print(f"\n  Fold {fold_k} summary:")
    print(fold_summary[["RMSE","R2","F1_or_Acc","AUC"]].mean(numeric_only=True).to_string())


# ── Aggregate across folds ─────────────────────────────────────────────
print("\n" + "="*60)
print("  Aggregating CV results")
print("="*60)

all_folds_df = pd.DataFrame(all_fold_metrics)

per_variable_cv = (
    all_folds_df
    .groupby("Variable", sort=True)
    .agg(
        RMSE_mean=("RMSE",      "mean"), RMSE_var=("RMSE",      "var"),
        R2_mean  =("R2",        "mean"), R2_var  =("R2",        "var"),
        F1_mean  =("F1_or_Acc", "mean"), F1_var  =("F1_or_Acc", "var"),
        AUC_mean =("AUC",       "mean"), AUC_var =("AUC",       "var"),
    )
    .reset_index()
)

per_fold_means = (
    all_folds_df
    .groupby("fold")
    .agg(RMSE=("RMSE","mean"), R2=("R2","mean"),
         F1_or_Acc=("F1_or_Acc","mean"), AUC=("AUC","mean"))
    .reset_index()
)
overall_cv = pd.DataFrame([{
    "RMSE_mean": per_fold_means["RMSE"].mean(),
    "RMSE_var":  per_fold_means["RMSE"].var(),
    "R2_mean":   per_fold_means["R2"].mean(),
    "R2_var":    per_fold_means["R2"].var(),
    "F1_mean":   per_fold_means["F1_or_Acc"].mean(),
    "F1_var":    per_fold_means["F1_or_Acc"].var(),
    "AUC_mean":  per_fold_means["AUC"].mean(),
    "AUC_var":   per_fold_means["AUC"].var(),
}])

print("\nPer-variable CV results:")
print(per_variable_cv.to_string(index=False))
print("\nOverall CV results (mean & variance across 5 folds):")
print(overall_cv.to_string(index=False))


# ── Save ───────────────────────────────────────────────────────────────
all_folds_df.to_csv(   os.path.join(OUT_DIR, "cv_all_folds_metrics.csv"),    index=False)
per_variable_cv.to_csv(os.path.join(OUT_DIR, "cv_per_variable_metrics.csv"), index=False)
overall_cv.to_csv(     os.path.join(OUT_DIR, "cv_overall_metrics.csv"),      index=False)

print("\n✓ Saved:")
print(f"  {os.path.join(OUT_DIR, 'cv_all_folds_metrics.csv')}")
print(f"  {os.path.join(OUT_DIR, 'cv_per_variable_metrics.csv')}")
print(f"  {os.path.join(OUT_DIR, 'cv_overall_metrics.csv')}")