# tabnet_regression_5fold_cv_full.py
# -------------------------------------------------------
# TabNet regressor: 5-fold CV for continuous toxins
# Pretraining variant: FULL
#   - Encoder pretrained ONCE on all X (train+test) before the CV loop
#   - Pretrained weights cloned into a fresh regressor each fold
#   - Matches the "full autoencoder" approach in the R transfer learning scripts
#
# Outputs:
#   tabnet_cont_full_cv_all_folds_metrics.csv
#   tabnet_cont_full_cv_per_variable_metrics.csv
#   tabnet_cont_full_cv_overall_metrics.csv
# -------------------------------------------------------

import os, random, copy
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from pytorch_tabnet.tab_model import TabNetRegressor
from pytorch_tabnet.pretraining import TabNetPretrainer

# ── Config (inlined from tabnet_config.py) ────────────────────────────────────
BASE_DIR   = "/Users/alaninglis/Desktop/Transfer Learning models/TabNET"
DATA_DIR   = os.path.join(BASE_DIR, "data")
RESULTS_DIR= os.path.join(BASE_DIR, "tabnet_results_cv")
OUT_DIR    = os.path.join(RESULTS_DIR, "regression_full")
os.makedirs(OUT_DIR, exist_ok=True)

# Fold assignments come from the shared CSV generated by the baseline R script
FOLD_CSV   = "/Users/alaninglis/Desktop/Mycotoxin Paper Final/fold_assignments.csv"
X_CSV      = "/Users/alaninglis/Desktop/Mycotoxin Paper Final/x.csv"
YCONT_CSV  = "/Users/alaninglis/Desktop/Mycotoxin Paper Final/y_cont.csv"

SEED     = 1701
N_FOLDS  = 5
VAL_FRAC = 0.15

CONTINUOUS_TOXINS = [
    "DON", "D3G", "Nivalenol", "3-AC-DON", "15-AC-DON", "T-2_toxin",
    "HT-2_toxin", "T2G", "Neos", "ENN_A1", "ENN_A", "ENN_B",
    "ENN_B1", "BEAU", "ZEN", "Apicidin", "STER", "DAS",
    "Quest", "AOH", "AME", "MON", "Ergocristine", "EGT",
]

TABNET_ARCH = dict(
    n_d           = 32,
    n_a           = 32,
    n_steps       = 5,
    gamma         = 1.3,
    lambda_sparse = 1e-4,
    momentum      = 0.02,
)

FIT_PARAMS = dict(
    max_epochs         = 200,
    patience           = 20,
    batch_size         = 256,
    virtual_batch_size = 128,
    num_workers        = 0,
)

PRETRAIN_PARAMS = dict(
    max_epochs         = 100,
    patience           = 15,
    batch_size         = 256,
    virtual_batch_size = 128,
    num_workers        = 0,
    pretraining_ratio  = 0.5,
)

# ── Helpers ───────────────────────────────────────────────────────────────────
def set_seeds(seed):
    import torch
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark     = False

def rmse_fn(y_true, y_pred):
    try:
        from sklearn.metrics import root_mean_squared_error
        return float(root_mean_squared_error(y_true.ravel(), y_pred.ravel()))
    except ImportError:
        from sklearn.metrics import mean_squared_error
        return float(np.sqrt(mean_squared_error(y_true.ravel(), y_pred.ravel())))

def resolve_batch_size(n, requested=256, virtual=128):
    bs  = min(requested, max(32, n // 4))
    vbs = min(virtual, bs // 2)
    vbs = max(vbs, 1)
    return bs, vbs

set_seeds(SEED)

# ── Load data ─────────────────────────────────────────────────────────────────
print("Loading data...")
X_df    = pd.read_csv(X_CSV)
Yc_df   = pd.read_csv(YCONT_CSV)
fold_df = pd.read_csv(FOLD_CSV)

X_np  = X_df.select_dtypes(include=[np.number]).values.astype(np.float32)
Yc_np = Yc_df.reindex(columns=CONTINUOUS_TOXINS).values.astype(np.float32)
fold_assignments = fold_df["fold"].values

assert len(fold_df) == len(X_np), \
    f"fold_assignments.csv has {len(fold_df)} rows but X has {len(X_np)}"

if np.isnan(X_np).any():
    raise ValueError("Predictor matrix contains NaNs — TabNet requires finite inputs.")

print(f"Data: {X_np.shape[0]} rows x {X_np.shape[1]} features, {len(CONTINUOUS_TOXINS)} toxins")

# ── Step 1: Pretrain encoder ONCE on full X ───────────────────────────────────
print("\n" + "="*60)
print("  Pretraining encoder on full X (all rows)...")
print("="*60)

set_seeds(SEED)
pretrainer = TabNetPretrainer(
    **TABNET_ARCH,
    seed        = SEED,
    verbose     = 1,
    device_name = "cpu",
)
pretrainer.fit(X_np, eval_set=[], **PRETRAIN_PARAMS)

# Save pretrained weights to disk so each fold can load a fresh copy
pretrain_save_path = os.path.join(OUT_DIR, "tabnet_pretrained_full")
pretrainer.save_model(pretrain_save_path)
print(f"  ✓ Pretrained encoder saved → {pretrain_save_path}.zip")

# ── Step 2: 5-Fold CV ─────────────────────────────────────────────────────────
all_fold_metrics = []

for fold_k in range(1, N_FOLDS + 1):
    print(f"\n{'='*60}")
    print(f"  Fold {fold_k} / {N_FOLDS}")
    print(f"{'='*60}")

    set_seeds(SEED + fold_k)

    test_mask  = (fold_assignments == fold_k)
    train_mask = ~test_mask

    X_train_fold = X_np[train_mask]
    X_test_fold  = X_np[test_mask]
    Yc_train     = Yc_np[train_mask]
    Yc_test      = Yc_np[test_mask]

    print(f"  Train: {X_train_fold.shape[0]} rows | Test: {X_test_fold.shape[0]} rows")

    for j, tox in enumerate(CONTINUOUS_TOXINS):
        y_tr_full = Yc_train[:, j]
        y_te_full = Yc_test[:, j]

        tr_mask = ~np.isnan(y_tr_full)
        te_mask = ~np.isnan(y_te_full)

        if tr_mask.sum() < 10:
            print(f"  Skipping {tox}: <10 training rows")
            all_fold_metrics.append(dict(
                fold=fold_k, Variable=tox, RMSE=np.nan, R2=np.nan))
            continue

        X_tr_all = X_train_fold[tr_mask]
        y_tr_all = y_tr_full[tr_mask]
        X_te_obs = X_test_fold[te_mask]
        y_te_obs = y_te_full[te_mask]

        # Val split from training fold only (no leakage)
        X_tr, X_val, y_tr, y_val = train_test_split(
            X_tr_all, y_tr_all,
            test_size=VAL_FRAC, random_state=SEED + fold_k
        )

        bs, vbs = resolve_batch_size(len(y_tr),
                                     FIT_PARAMS["batch_size"],
                                     FIT_PARAMS["virtual_batch_size"])

        # Load fresh pretrained encoder for this toxin/fold
        fresh_pretrainer = TabNetPretrainer(
            **TABNET_ARCH, seed=SEED + fold_k, device_name="cpu")
        fresh_pretrainer.load_model(pretrain_save_path + ".zip")

        reg = TabNetRegressor(
            **TABNET_ARCH,
            seed        = SEED + fold_k,
            verbose     = 0,
            device_name = "cpu",
        )
        reg.fit(
            X_train           = X_tr,
            y_train           = y_tr.reshape(-1, 1),
            eval_set          = [(X_val, y_val.reshape(-1, 1))],
            eval_metric       = ["rmse"],
            max_epochs        = FIT_PARAMS["max_epochs"],
            patience          = FIT_PARAMS["patience"],
            batch_size        = bs,
            virtual_batch_size= vbs,
            num_workers       = FIT_PARAMS["num_workers"],
            from_unsupervised = fresh_pretrainer,
        )

        preds = reg.predict(X_te_obs).ravel()
        rmse_val = rmse_fn(y_te_obs, preds)
        r2_val   = float(r2_score(y_te_obs, preds)) if len(np.unique(y_te_obs)) > 1 else np.nan

        all_fold_metrics.append(dict(
            fold=fold_k, Variable=tox, RMSE=rmse_val, R2=r2_val))
        print(f"  {tox}: RMSE={rmse_val:.4f}  R2={r2_val:.4f}")

    # Save incrementally after each fold
    pd.DataFrame(all_fold_metrics).to_csv(
        os.path.join(OUT_DIR, "tabnet_cont_full_cv_all_folds_metrics.csv"), index=False)
    print(f"  ✓ Fold {fold_k} saved")

# ── Aggregate ─────────────────────────────────────────────────────────────────
print("\n" + "="*60)
print("  Aggregating results...")
print("="*60)

all_folds_df = pd.DataFrame(all_fold_metrics)

per_variable_cv = (
    all_folds_df
    .groupby("Variable", sort=True)
    .agg(
        RMSE_mean=("RMSE", "mean"), RMSE_var=("RMSE", "var"),
        R2_mean  =("R2",   "mean"), R2_var  =("R2",   "var"),
    )
    .reset_index()
)

per_fold_means = (
    all_folds_df.groupby("fold")
    .agg(RMSE=("RMSE", "mean"), R2=("R2", "mean"))
    .reset_index()
)
overall_cv = pd.DataFrame([{
    "RMSE_mean": per_fold_means["RMSE"].mean(),
    "RMSE_var":  per_fold_means["RMSE"].var(),
    "R2_mean":   per_fold_means["R2"].mean(),
    "R2_var":    per_fold_means["R2"].var(),
}])

print("\nPer-variable CV results:")
print(per_variable_cv.to_string(index=False))
print("\nOverall CV results:")
print(overall_cv.to_string(index=False))

all_folds_df.to_csv(   os.path.join(OUT_DIR, "tabnet_cont_full_cv_all_folds_metrics.csv"),    index=False)
per_variable_cv.to_csv(os.path.join(OUT_DIR, "tabnet_cont_full_cv_per_variable_metrics.csv"), index=False)
overall_cv.to_csv(     os.path.join(OUT_DIR, "tabnet_cont_full_cv_overall_metrics.csv"),      index=False)

print(f"\n✓ All results saved to: {OUT_DIR}")